name: "PM5003 Sensor"
version: "1.0.7"
slug: pm5003
description: "Home Assistant add-on for Pimoroni PM5003 particulate matter sensor"
arch:
  - amd64
  - armv7
  - aarch64
url: "https://github.com/neild3r/ha-pm5003"
init: false
options:
  device: "/dev/ttyAMA0"
  baudrate: 9600
  poll_interval: 10
  pin_enable: "GPIO22"
  pin_reset: "GPIO27"
schema:
  device: str
  baudrate: int
  poll_interval: int
  pin_enable: str
  pin_reset: str
uart: true
gpio: true